CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(30),
  "email" varchar(50) UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "age" int NOT NULL,
  "role" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(30),
  "description" text,
  "level" varchar(50) NOT NULL,
  "teacher" varchar(50) NOT NULL,
  "course_id" int,
  "category_id" int
);

CREATE TABLE "course_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" varchar(30),
  "url" text UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(30) NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(30) NOT NULL
);IBN

CREATE TABLE "pivote_courses_categories" (
  "category_id" int,
  "course_id" int
);

ALTER TABLE "courses" ADD FOREIGN KEY ("title") REFERENCES "users" ("id");

ALTER TABLE "pivote_courses_categories" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "pivote_courses_categories" ADD FOREIGN KEY ("course_id") REFERENCES "course_video" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("role") REFERENCES "roles" ("id");

INSERT INTO roles VALUES (1, 'student'), (2, 'teacher'), (3, 'admin');

INSERT INTO users VALUES (1, 'Martha', 'martha@gmail.com', '345mar', 43, 2);

INSERT INTO users VALUES (2, 'Daniel', 'dan@gmail.com', '345dan', 23, 1);

INSERT INTO categories VALUES (1, 'Maths'), (2, 'Biology');

INSERT INTO courses VALUES (1, 'Maths', 'Algebra and specificis funtions', 'Medium', 'Marhta', 1, 1), (2, 'Biology', 'Periodic table and chemestry', 'Medium', 'Marhta', 1, 2);

INSERT INTO course_video VALUES (1, 'Maths', '..//..'), (2, 'Biology', '..//..');